default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: my_wallet_repo_development

test:
  <<: *default
  database: my_wallet_repo_test

production:
  <<: *default
  database: my_wallet_repo_production
  username: my_wallet_repo
  password: <%= ENV['MY_WALLET_REPO_DATABASE_PASSWORD'] %>
