# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3bd2a5bbf7b17640399b3fa1fa4b75d8783d005cdc9acabb294fa91415bd795aa334de7c039324e3af0d9e6fdad0c4df7f713a5fb99bb1fd05b9aef7567cf7f2

test:
  secret_key_base: b7be09568b64f158555846ebb25dc17957945c6006111a400f1fed9fac746a1e39f617c03e9831c25d473fec8cc0cbef6b22c3b71c82416e8973bd1306421a84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
